# Generated by Django 2.2.16 on 2022-11-10 14:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221110_2137'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_unique_relationships',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='%(app_label)s_%(class)s_prevent_self_follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='%(app_label)s_%(class)s_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='%(app_label)s_%(class)s_prevent_self_follow'),
        ),
    ]
